version: '3.3'
services:
    db:
        image: mariadb:10.4
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql
            - .devcontainer/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_DATABASE: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
            MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
        # ports:
        #     - '3306:3306'
        #Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)
    web:
        image: wordpress 
        restart: unless-stopped
        environment:
            - WORDPRESS_DB_PASSWORD=mariadb
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=mariadb
            - WORDPRESS_DB_NAME=mariadb
            - UPLOAD_LIMIT=64M
        ports:
            - "80:80"
        volumes:
            #- './html:/var/www/html'
            - ./html:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

# volumes:
#   wordpress_tmp:
#   wordpress_db: